### ISSUE TITLE
HTML page will not render if $ref to external document is used

### ISSUE THREAD

**Issue by malidiab** [open-rpc/playground#216]
using $ref to external document will fail to render the document ( empty page , fail without errors ). I would suggest that it just put the document name there and still render the rest of the page.
"schema": {
                    "description": "",
                    "$ref": "somedocument.json"                    
                }

**Comment by shanejonas** [comment]
external refs from the playground should be absolute urls. since somedocument.json would resolve to playground.open-rpc.org/somedocument.json which doesn’t exist.
 
you can find out more how json schema refs work here:
https://github.com/APIDevTools/json-schema-ref-parser/blob/master/README.md#the-problem
